apiVersion: v1
kind: Service
metadata:
  name: {{ include "PAMv1.fullname" . }}
  labels:
    {{- include "PAMv1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "PAMv1.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: ssh
