apiVersion: apps/v1
kind: Deployment
metadata:
  name: pam-server
  namespace: pamv1
  labels:
    app.kubernetes.io/name: pamv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pamv1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pamv1
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pam-server
          image: ghcr.io/morandeirachema/pamv1:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: pam-secrets
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
