apiVersion: v1
kind: Secret
metadata:
    name: pam-secrets
    namespace: pamv1
type: Opaque
stringData:
    PAM_MASTER_KEY: ENC[AES256_GCM,data:iU6OwmfcC1CR0OS1TFIHAZZQf+KZvTcYCqxtIQlOfdKYsolckI8=,iv:BBfZNfoEOQKpFenZjdfOxTCDZAHUvaUvwKLZQ4hmsi0=,tag:zGfWh9YLeoPYvra28VqhVA==,type:str]
    PAM_API_KEY: ENC[AES256_GCM,data:2awxmrE17IXUmuxBRcAN+ZMveFUCaxfOGugpz2Nw3iU7bwYjQSA=,iv:OYu7Y3+AtHuWDSXzkl7EXjKA9877YCkCmFc+cA4dj2U=,tag:ys6ojFmcugofpMj7KW++jA==,type:str]
    PAM_BREAK_GLASS_KEY_HASH: ""
    PAM_DATABASE_URL: ENC[AES256_GCM,data:DuWLpZDKgUvYkjuVsxwtn67R61/Sb8oKOqdxoHqy19bbDP50GjPExniVpa/5sbzULsZqj7sGYzPnisiZzSo=,iv:gmSllNbgSHeBMgv8AQn5mCrPP7KbDTWuRLBcoeY4aVM=,tag:BXgOYBmY+LXtQVHnvi5Ppg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYkFmQlVkNnFZR0xKM0U0
            Z3VGWWpWOGhockV6UXUxWVNlZlNmZ1hkRDFjCi9wUWRVR2JMWkhHOEdzOENLNHEr
            NERTQy9SWDJmaWh3VVlLc0p3T2YvbGsKLS0tIDM0eEw2RE55cy9Ra0tuOE9aQmRu
            TXU0Rlk2UGIvbVpHZTdXb1NSSFhLWjAKGl+DpDncLcL6tHgqQNmKuPoKUXmZVLCn
            KIl5Px9tm6mkLIE0wiIa9/Q2xhvxYdOM3Ei7kBmAc0tPjljZQk8ehg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pfn57mnl9gg6c5tu05tgaym2jk8kzgxnwf20hd008lzghsp6vyrqetlmny
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T10:20:20Z"
    mac: ENC[AES256_GCM,data:q7zjEXeklxYe+Ng2PURs4hchTvBEw3/IdOFXFokQ2UbaqMhslEjzNA5LgPY8Q5f17kmhc5nONeR3e7THNwohrEH3BWRLD1GBL8MckgcBToDDdEHfsJTyEoGHB4ktdA21rIR/YHFNfki0/Dr/40lkx7oevQxceg1b1zbyesdm/2E=,iv:OGjyGBqdzTtVVk7kiEhKU28It8I7DxJ0a/N+qL0Fqns=,tag:q77raYEZQzPWm5K51fw8zA==,type:str]
    version: 3.13.2
